name: Run Biber

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup LaTeX and Biber
        run: |
          sudo apt-get update -q
          sudo apt-get install -y texlive-xetex texlive-bibtex-extra

      - name: Run Biber
        uses: michaeltimbs/action-biber@v1
        with:
          args: lahti
