name: Compile LaTeX Document

on:
  push:
    branches:
      - master
    paths:
      - '**.tex'
      - '**.yml'
      - '**.bib'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: lahti.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: lahti.aux
          compiler: bibtex
          args: 
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: lahti.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape