name: Compile LaTeX Document

on:
  push:
    branches:
      - master
    paths:
      - '**.tex'
      - '**.yml'
      - '**.bib'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile with pdflatex
        uses: dante-ev/latex-action@latest
        with:
          root_file: lahti.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      - name: Run biber
        uses: dante-ev/latex-action@latest
        with:
          root_file: lahti
          compiler: biber

      - name: Compile again with pdflatex
        uses: dante-ev/latex-action@latest
        with:
          root_file: lahti.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      - name: Final pdflatex run
        uses: dante-ev/latex-action@latest
        with:
          root_file: lahti.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape