name: Compile LaTeX Document

on:
  push:
    branches:
      - main
    paths:
      - '*.tex'
      - '*.bib'

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v2
        with:
          root_file: lahti.tex

      - name: Compile LaTeX Document
        run: |
          latexmk -pdf -interaction=nonstopmode -file-line-error main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: Compiled-PDF
          path: lahti.pdf
