name: Compile LaTeX Document

on:
  push:
    branches:
      - master
    paths:
      - "**.tex"
      - "**.yml"
      - "**.bib"
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment
        run: source venv/bin/activate

      - name: Upgrade setuptools
        run: pip install --upgrade setuptools

      - name: Install dependencies
        run: pip install pybtex

      - name: Run Python script
        run: python convert_bib_to_pdf.py
        working-directory: ./scripts

      - name: Move PDF to current directory
        run: mv ./scripts/lahti.pdf ./lahti.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdf-artifact
          path: ./lahti.pdf
