name: Compile LaTeX Document

on:
  push:
    branches:
      - master
    paths:
      - "**.yml"
      - "**.bib"
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install pybtex reportlab

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-bibtex-extra biber

      - name: Run Python Script
        run: python3 convert_bib_to_pdf.py

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: generated-pdf
          path: Leo_Lahti.pdf
