name: Convert BibTeX to PDF

on:
  push:
    branches: 
      - master
    paths:
      - '**.bib'  # Trigger the workflow on push events that include .bib files
      - '**.yml'
      - '**.sh'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up TeX Live
      uses: xu-cheng/latex-action@v2
      with:
        root_file: lahti.tex

    - name: Compile LaTeX document
      run: |
        pdflatex -interaction=nonstopmode lahti.tex
        bibtex lahti
        pdflatex -interaction=nonstopmode lahti.tex
        pdflatex -interaction=nonstopmode lahti.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-PDF
        path: document.pdf
